/*
 * PhoenixonControls_GPIO.c
 *
 *  Created on: 2018. 5. 19.
 *      Author: BGKim
 */
#include "../../../common/include/F28x_Project.h"
#include "../../../common/include/driverlib.h"
#include "../../../common/include/device.h"

void DSP_GpioInit(void)
{
	Device_initGPIO();

	GPIO_setPinConfig(GPIO_0_GPIO0);		//DSP_GPIO00_O_OUTPUT_MASTER_CHARGE
	GPIO_setPinConfig(GPIO_1_GPIO1);        //DSP_GPIO01_O_OUTPUT_SLAVE_CHARGE
	GPIO_setPinConfig(GPIO_2_GPIO2);        //DSP_GPIO02_O_OUTPUT_MASTER_DISCHARGE
	GPIO_setPinConfig(GPIO_3_GPIO3);        //DSP_GPIO03_O_OUTPUT_SLAVE_DISCHARGE
	GPIO_setPinConfig(GPIO_4_GPIO4);        //DSP_GPIO04_O_OPMODE_MASTER_SEL0
	GPIO_setPinConfig(GPIO_5_GPIO5);        //DSP_GPIO05_O_OPMODE_MASTER_SEL1
	GPIO_setPinConfig(GPIO_6_GPIO6);        //DSP_GPIO06_O_OPMODE_SLAVE_SEL0
	GPIO_setPinConfig(GPIO_7_GPIO7);        //DSP_GPIO07_O_OPMODE_SLAVE_SEL1
	GPIO_setPinConfig(GPIO_8_GPIO8);        //DSP_GPIO08_O_INTG_MASTER_SEL0
	GPIO_setPinConfig(GPIO_9_GPIO9);        //DSP_GPIO09_O_INTG_MASTER_SEL1
	GPIO_setPinConfig(GPIO_50_GPIO50);      //DSP_GPIO50_O_INTG_MASTER_SEL1
	GPIO_setPinConfig(GPIO_10_GPIO10);      //DSP_GPIO10_O_INTG_RESET_SEL0
	GPIO_setPinConfig(GPIO_11_GPIO11);      //DSP_GPIO11_O_INTG_RESET_SEL1
	GPIO_setPinConfig(GPIO_12_GPIO12);      //DSP_GPIO12_O_INTG_SLAVE_SEL0
	GPIO_setPinConfig(GPIO_13_GPIO13);      //DSP_GPIO13_O_INTG_SLAVE_SEL1
	GPIO_setPinConfig(GPIO_51_GPIO51);      //DSP_GPIO51_O_INTG_SLAVE_SEL1
	GPIO_setPinConfig(GPIO_52_GPIO52);      //DSP_GPIO52_O_INTG_CHARGE_SEL0
	GPIO_setPinConfig(GPIO_53_GPIO53);      //DSP_GPIO53_O_INTG_CHARGE_SEL1
	GPIO_setPinConfig(GPIO_14_GPIO14);      //DSP_GPIO14_I_MASTER_RDAC_RDY()
	GPIO_setPinConfig(GPIO_15_GPIO15);      //DSP_GPIO15_I_SLAVE_RDAC_RDY()
	GPIO_setPinConfig(GPIO_19_GPIO19);      //DSP_GPIO19_O_ENABLE_IO_1()
	GPIO_setPinConfig(GPIO_20_GPIO20);      //DSP_GPIO20_O_ENABLE_IO_0()
	GPIO_setPinConfig(GPIO_32_GPIO32);      //DSP_GPIO32_I_EXT_SYNCH_SLAVE_IN()
	GPIO_setPinConfig(GPIO_33_GPIO33);      //DSP_GPIO33_O_EXT_SYNCH_MASTER
	GPIO_setPinConfig(GPIO_42_GPIO42);      //DSP_GPIO42_O_N_MASTER_DIS_EN1
	GPIO_setPinConfig(GPIO_43_GPIO43);      //DSP_GPIO43_O_N_MASTER_DIS_EN0
	GPIO_setPinConfig(GPIO_44_GPIO44);      //DSP_GPIO44_O_N_MASTER_CHG_EN1
	GPIO_setPinConfig(GPIO_45_GPIO45);      //DSP_GPIO45_O_N_MASTER_CHG_EN0
	GPIO_setPinConfig(GPIO_46_GPIO46);      //DSP_GPIO46_O_N_SLAVE_DIS_EN1
	GPIO_setPinConfig(GPIO_47_GPIO47);      //DSP_GPIO47_O_N_SLAVE_DIS_EN0
	GPIO_setPinConfig(GPIO_48_GPIO48);      //DSP_GPIO48_O_N_SLAVE_CHG_EN1
	GPIO_setPinConfig(GPIO_49_GPIO49);      //DSP_GPIO49_O_N_SLAVE_CHG_EN0
	GPIO_setPinConfig(GPIO_54_GPIO54);      //DSP_GPIO54_O_DIO_PORT_1_IN
	GPIO_setPinConfig(GPIO_55_GPIO55);      //DSP_GPIO55_O_DIO_PORT_0_IN
	GPIO_setPinConfig(GPIO_56_GPIO56);      //DSP_GPIO56_O_P_VOLATAGE_RELAY
	GPIO_setPinConfig(GPIO_57_GPIO57);      //DSP_GPIO57_O_N_VOLATAGE_RELAY
	GPIO_setPinConfig(GPIO_58_GPIO58);      //DSP_GPIO58_O_ADC_OS0
	GPIO_setPinConfig(GPIO_59_GPIO59);      //DSP_GPIO59_O_ADC_OS1
	GPIO_setPinConfig(GPIO_60_GPIO60);      //DSP_GPIO60_O_ADC_OS2
	GPIO_setPinConfig(GPIO_61_GPIO61);      //DSP_GPIO61_I_ADC_BUSY()
	GPIO_setPinConfig(GPIO_62_GPIO62);      //DSP_GPIO62_O_ADC_N_CS
	GPIO_setPinConfig(GPIO_63_GPIO63);      //DSP_GPIO63_I_ADC_FRSTD()
	GPIO_setPinConfig(GPIO_64_GPIO64);      //DSP_GPIO64_O_ADC_RESET
	GPIO_setPinConfig(GPIO_88_GPIO88);      //DSP_GPIO88_O_ADC_RANGE
	GPIO_setPinConfig(GPIO_65_GPIO65);      //DSP_GPIO65_I_EMERGENCY_IN()
	GPIO_setPinConfig(GPIO_66_GPIO66);      //DSP_GPIO66_O_DAC_A0
	GPIO_setPinConfig(GPIO_67_GPIO67);      //DSP_GPIO67_O_DAC_A1
	GPIO_setPinConfig(GPIO_68_GPIO68);      //DSP_GPIO68_O_DAC_FINE_I_N_RESET
	GPIO_setPinConfig(GPIO_86_GPIO86);      //DSP_GPIO86_O_DAC_V_N_RESET
	GPIO_setPinConfig(GPIO_87_GPIO87);      //DSP_GPIO87_O_DAC_I_N_RESET
	GPIO_setPinConfig(GPIO_89_GPIO89);      //DSP_GPIO89_O_MASTER_RDAC_N_RESET
	GPIO_setPinConfig(GPIO_90_GPIO90);      //DSP_GPIO90_O_MASTER_RDAC_N_CS
	GPIO_setPinConfig(GPIO_91_GPIO91);      //DSP_GPIO91_O_MASTER_RDAC_N_RESET
	GPIO_setPinConfig(GPIO_93_GPIO93);      //DSP_GPIO93_O_MASTER_RDAC_N_CS
	GPIO_setPinConfig(GPIO_94_GPIO94);      //DSP_GPIO94_O_N_RLYON_1
	GPIO_setPinConfig(GPIO_99_GPIO99);      //DSP_GPIO99_O_N_RLYON_0
	GPIO_setPinConfig(GPIO_133_GPIO133);    //DSP_GPIO133_O_DSP_STATUS

	GPIO_setPinConfig(GPIO_16_SPISIMOA);	//DSP_GPIO16_SPISIMOA
	GPIO_setPinConfig(GPIO_17_SPISOMIA);    //DSP_GPIO17_SPISOMIA
	GPIO_setPinConfig(GPIO_18_SPICLKA);     //DSP_GPIO18_SPICLKA
	GPIO_setPinConfig(GPIO_22_SCITXDB);     //DSP_GPIO22_SCITXDB
	GPIO_setPinConfig(GPIO_23_SCIRXDB);     //DSP_GPIO23_SCIRXDB
	GPIO_setPinConfig(GPIO_24_SPISIMOB);    //DSP_GPIO24_SPISIMOB
	GPIO_setPinConfig(GPIO_25_SPISOMIB);    //DSP_GPIO25_SPISOMIB
	GPIO_setPinConfig(GPIO_26_SPICLKB);     //DSP_GPIO26_SPICLKB
	GPIO_setPinConfig(GPIO_27_SPISTEB);     //DSP_GPIO27_SPISTEB
	GPIO_setPinConfig(GPIO_28_SCIRXDA);     //DSP_GPIO28_SCIRXDA
	GPIO_setPinConfig(GPIO_29_SCITXDA);     //DSP_GPIO29_SCITXDA
	GPIO_setPinConfig(GPIO_85_EM1D0);       //DSP_GPIO85_DSP_XD0
	GPIO_setPinConfig(GPIO_83_EM1D1);       //DSP_GPIO83_DSP_XD1
	GPIO_setPinConfig(GPIO_82_EM1D2);       //DSP_GPIO82_DSP_XD2
	GPIO_setPinConfig(GPIO_81_EM1D3);       //DSP_GPIO81_DSP_XD3
	GPIO_setPinConfig(GPIO_80_EM1D4);       //DSP_GPIO80_DSP_XD4
	GPIO_setPinConfig(GPIO_79_EM1D5);       //DSP_GPIO79_DSP_XD5
	GPIO_setPinConfig(GPIO_78_EM1D6);       //DSP_GPIO78_DSP_XD6
	GPIO_setPinConfig(GPIO_77_EM1D7);       //DSP_GPIO77_DSP_XD7
	GPIO_setPinConfig(GPIO_76_EM1D8);       //DSP_GPIO76_DSP_XD8
	GPIO_setPinConfig(GPIO_75_EM1D9);       //DSP_GPIO75_DSP_XD9
	GPIO_setPinConfig(GPIO_74_EM1D10);      //DSP_GPIO74_DSP_XD10
	GPIO_setPinConfig(GPIO_73_EM1D11);      //DSP_GPIO73_DSP_XD11
	GPIO_setPinConfig(GPIO_72_EM1D12);      //DSP_GPIO72_DSP_XD12
	GPIO_setPinConfig(GPIO_71_EM1D13);      //DSP_GPIO71_DSP_XD13
	GPIO_setPinConfig(GPIO_70_EM1D14);      //DSP_GPIO70_DSP_XD14
	GPIO_setPinConfig(GPIO_69_EM1D15);      //DSP_GPIO69_DSP_XD15
	GPIO_setPinConfig(GPIO_92_EM1BA1);      //DSP_GPIO92_DSP_XA0
	GPIO_setPinConfig(GPIO_38_EM1A0);       //DSP_GPIO38_DSP_XA0(1)
	GPIO_setPinConfig(GPIO_39_EM1A1);       //DSP_GPIO39_DSP_XA1(2)
	GPIO_setPinConfig(GPIO_40_EM1A2);       //DSP_GPIO40_DSP_XA2(3)
	GPIO_setPinConfig(GPIO_41_EM1A3);       //DSP_GPIO41_DSP_XA3(4)
	GPIO_setPinConfig(GPIO_34_EM1CS2N);     //DSP_GPIO34_N_CS2
	GPIO_setPinConfig(GPIO_37_EM1OEN);      //DSP_GPIO37_N_XRD
	GPIO_setPinConfig(GPIO_31_EM1WEN);      //DSP_GPIO31_N_XWE


	GPIO_setDirectionMode(0, GPIO_DIR_MODE_OUT);		//DSP_GPIO00_O_OUTPUT_MASTER_CHARGE
	GPIO_setDirectionMode(1, GPIO_DIR_MODE_OUT);        //DSP_GPIO01_O_OUTPUT_SLAVE_CHARGE
	GPIO_setDirectionMode(2, GPIO_DIR_MODE_OUT);        //DSP_GPIO02_O_OUTPUT_MASTER_DISCHARGE
	GPIO_setDirectionMode(3, GPIO_DIR_MODE_OUT);        //DSP_GPIO03_O_OUTPUT_SLAVE_DISCHARGE
	GPIO_setDirectionMode(4, GPIO_DIR_MODE_OUT);        //DSP_GPIO04_O_OPMODE_MASTER_SEL0
	GPIO_setDirectionMode(5, GPIO_DIR_MODE_OUT);        //DSP_GPIO05_O_OPMODE_MASTER_SEL1
	GPIO_setDirectionMode(6, GPIO_DIR_MODE_OUT);        //DSP_GPIO06_O_OPMODE_SLAVE_SEL0
	GPIO_setDirectionMode(7, GPIO_DIR_MODE_OUT);        //DSP_GPIO07_O_OPMODE_SLAVE_SEL1
	GPIO_setDirectionMode(8, GPIO_DIR_MODE_OUT);        //DSP_GPIO08_O_INTG_MASTER_SEL0
	GPIO_setDirectionMode(9, GPIO_DIR_MODE_OUT);        //DSP_GPIO09_O_INTG_MASTER_SEL1
	GPIO_setDirectionMode(50, GPIO_DIR_MODE_OUT);       //DSP_GPIO50_O_INTG_MASTER_SEL1
	GPIO_setDirectionMode(10, GPIO_DIR_MODE_OUT);       //DSP_GPIO10_O_INTG_RESET_SEL0
	GPIO_setDirectionMode(11, GPIO_DIR_MODE_OUT);       //DSP_GPIO11_O_INTG_RESET_SEL1
	GPIO_setDirectionMode(12, GPIO_DIR_MODE_OUT);       //DSP_GPIO12_O_INTG_SLAVE_SEL0
	GPIO_setDirectionMode(13, GPIO_DIR_MODE_OUT);       //DSP_GPIO13_O_INTG_SLAVE_SEL1
	GPIO_setDirectionMode(51, GPIO_DIR_MODE_OUT);       //DSP_GPIO51_O_INTG_SLAVE_SEL1
	GPIO_setDirectionMode(52, GPIO_DIR_MODE_OUT);       //DSP_GPIO52_O_INTG_CHARGE_SEL0
	GPIO_setDirectionMode(53, GPIO_DIR_MODE_OUT);       //DSP_GPIO53_O_INTG_CHARGE_SEL1
	GPIO_setDirectionMode(14, GPIO_DIR_MODE_IN);        //DSP_GPIO14_I_MASTER_RDAC_RDY()
	GPIO_setDirectionMode(15, GPIO_DIR_MODE_IN);        //DSP_GPIO15_I_SLAVE_RDAC_RDY()
	GPIO_setDirectionMode(19, GPIO_DIR_MODE_OUT);       //DSP_GPIO19_O_ENABLE_IO_1()
	GPIO_setDirectionMode(20, GPIO_DIR_MODE_OUT);       //DSP_GPIO20_O_ENABLE_IO_0()
	GPIO_setDirectionMode(32, GPIO_DIR_MODE_IN);        //DSP_GPIO32_I_EXT_SYNCH_SLAVE_IN()
	GPIO_setDirectionMode(33, GPIO_DIR_MODE_OUT);       //DSP_GPIO33_O_EXT_SYNCH_MASTER
	GPIO_setDirectionMode(42, GPIO_DIR_MODE_OUT);       //DSP_GPIO42_O_N_MASTER_DIS_EN1
	GPIO_setDirectionMode(43, GPIO_DIR_MODE_OUT);       //DSP_GPIO43_O_N_MASTER_DIS_EN0
	GPIO_setDirectionMode(44, GPIO_DIR_MODE_OUT);       //DSP_GPIO44_O_N_MASTER_CHG_EN1
	GPIO_setDirectionMode(45, GPIO_DIR_MODE_OUT);       //DSP_GPIO45_O_N_MASTER_CHG_EN0
	GPIO_setDirectionMode(46, GPIO_DIR_MODE_OUT);       //DSP_GPIO46_O_N_SLAVE_DIS_EN1
	GPIO_setDirectionMode(47, GPIO_DIR_MODE_OUT);       //DSP_GPIO47_O_N_SLAVE_DIS_EN0
	GPIO_setDirectionMode(48, GPIO_DIR_MODE_OUT);       //DSP_GPIO48_O_N_SLAVE_CHG_EN1
	GPIO_setDirectionMode(49, GPIO_DIR_MODE_OUT);       //DSP_GPIO49_O_N_SLAVE_CHG_EN0
	GPIO_setDirectionMode(54, GPIO_DIR_MODE_OUT);       //DSP_GPIO54_O_DIO_PORT_1_IN
	GPIO_setDirectionMode(55, GPIO_DIR_MODE_OUT);       //DSP_GPIO55_O_DIO_PORT_0_IN
	GPIO_setDirectionMode(56, GPIO_DIR_MODE_OUT);       //DSP_GPIO56_O_P_VOLATAGE_RELAY
	GPIO_setDirectionMode(57, GPIO_DIR_MODE_OUT);       //DSP_GPIO57_O_N_VOLATAGE_RELAY
	GPIO_setDirectionMode(58, GPIO_DIR_MODE_OUT);       //DSP_GPIO58_O_ADC_OS0
	GPIO_setDirectionMode(59, GPIO_DIR_MODE_OUT);       //DSP_GPIO59_O_ADC_OS1
	GPIO_setDirectionMode(60, GPIO_DIR_MODE_OUT);       //DSP_GPIO60_O_ADC_OS2
	GPIO_setDirectionMode(61, GPIO_DIR_MODE_IN);        //DSP_GPIO61_I_ADC_BUSY()
	GPIO_setDirectionMode(62, GPIO_DIR_MODE_OUT);       //DSP_GPIO62_O_ADC_N_CS
	GPIO_setDirectionMode(63, GPIO_DIR_MODE_IN);        //DSP_GPIO63_I_ADC_FRSTD()
	GPIO_setDirectionMode(64, GPIO_DIR_MODE_OUT);       //DSP_GPIO64_O_ADC_RESET
	GPIO_setDirectionMode(88, GPIO_DIR_MODE_OUT);       //DSP_GPIO88_O_ADC_RANGE
	GPIO_setDirectionMode(65, GPIO_DIR_MODE_IN);        //DSP_GPIO65_I_EMERGENCY_IN()
	GPIO_setDirectionMode(66, GPIO_DIR_MODE_OUT);       //DSP_GPIO66_O_DAC_A0
	GPIO_setDirectionMode(67, GPIO_DIR_MODE_OUT);       //DSP_GPIO67_O_DAC_A1
	GPIO_setDirectionMode(68, GPIO_DIR_MODE_OUT);       //DSP_GPIO68_O_DAC_FINE_I_N_RESET
	GPIO_setDirectionMode(86, GPIO_DIR_MODE_OUT);       //DSP_GPIO86_O_DAC_V_N_RESET
	GPIO_setDirectionMode(87, GPIO_DIR_MODE_OUT);       //DSP_GPIO87_O_DAC_I_N_RESET
	GPIO_setDirectionMode(89, GPIO_DIR_MODE_OUT);       //DSP_GPIO89_O_MASTER_RDAC_N_RESET
	GPIO_setDirectionMode(90, GPIO_DIR_MODE_OUT);       //DSP_GPIO90_O_MASTER_RDAC_N_CS
	GPIO_setDirectionMode(91, GPIO_DIR_MODE_OUT);       //DSP_GPIO91_O_MASTER_RDAC_N_RESET
	GPIO_setDirectionMode(93, GPIO_DIR_MODE_OUT);       //DSP_GPIO93_O_MASTER_RDAC_N_CS
	GPIO_setDirectionMode(94, GPIO_DIR_MODE_OUT);       //DSP_GPIO94_O_N_RLYON_1
	GPIO_setDirectionMode(99, GPIO_DIR_MODE_OUT);       //DSP_GPIO99_O_N_RLYON_0
	GPIO_setDirectionMode(133, GPIO_DIR_MODE_OUT);      //DSP_GPIO133_O_DSP_STATUS

	GPIO_setDirectionMode(16, GPIO_DIR_MODE_OUT);       //DSP_GPIO16_SPISIMOA
	GPIO_setDirectionMode(17, GPIO_DIR_MODE_IN);        //DSP_GPIO17_SPISOMIA
	GPIO_setDirectionMode(18, GPIO_DIR_MODE_OUT);       //DSP_GPIO18_SPICLKA
	GPIO_setDirectionMode(22, GPIO_DIR_MODE_OUT);       //DSP_GPIO22_SCITXDB
	GPIO_setDirectionMode(23, GPIO_DIR_MODE_IN);        //DSP_GPIO23_SCIRXDB
	GPIO_setDirectionMode(24, GPIO_DIR_MODE_OUT);       //DSP_GPIO24_SPISIMOB
	GPIO_setDirectionMode(25, GPIO_DIR_MODE_IN);        //DSP_GPIO25_SPISOMIB
	GPIO_setDirectionMode(26, GPIO_DIR_MODE_OUT);       //DSP_GPIO26_SPICLKB
	GPIO_setDirectionMode(27, GPIO_DIR_MODE_OUT);       //DSP_GPIO27_SPISTEB
	GPIO_setDirectionMode(28, GPIO_DIR_MODE_IN);        //DSP_GPIO28_SCIRXDA
	GPIO_setDirectionMode(29, GPIO_DIR_MODE_OUT);       //DSP_GPIO29_SCITXDA
	GPIO_setDirectionMode(85, GPIO_DIR_MODE_IN);        //DSP_GPIO85_DSP_XD0
	GPIO_setDirectionMode(83, GPIO_DIR_MODE_IN);        //DSP_GPIO83_DSP_XD1
	GPIO_setDirectionMode(82, GPIO_DIR_MODE_IN);        //DSP_GPIO82_DSP_XD2
	GPIO_setDirectionMode(81, GPIO_DIR_MODE_IN);        //DSP_GPIO81_DSP_XD3
	GPIO_setDirectionMode(80, GPIO_DIR_MODE_IN);        //DSP_GPIO80_DSP_XD4
	GPIO_setDirectionMode(79, GPIO_DIR_MODE_IN);        //DSP_GPIO79_DSP_XD5
	GPIO_setDirectionMode(78, GPIO_DIR_MODE_IN);        //DSP_GPIO78_DSP_XD6
	GPIO_setDirectionMode(77, GPIO_DIR_MODE_IN);        //DSP_GPIO77_DSP_XD7
	GPIO_setDirectionMode(76, GPIO_DIR_MODE_IN);        //DSP_GPIO76_DSP_XD8
	GPIO_setDirectionMode(75, GPIO_DIR_MODE_IN);        //DSP_GPIO75_DSP_XD9
	GPIO_setDirectionMode(74, GPIO_DIR_MODE_IN);        //DSP_GPIO74_DSP_XD10
	GPIO_setDirectionMode(73, GPIO_DIR_MODE_IN);        //DSP_GPIO73_DSP_XD11
	GPIO_setDirectionMode(72, GPIO_DIR_MODE_IN);        //DSP_GPIO72_DSP_XD12
	GPIO_setDirectionMode(71, GPIO_DIR_MODE_IN);        //DSP_GPIO71_DSP_XD13
	GPIO_setDirectionMode(70, GPIO_DIR_MODE_IN);        //DSP_GPIO70_DSP_XD14
	GPIO_setDirectionMode(69, GPIO_DIR_MODE_IN);        //DSP_GPIO69_DSP_XD15
	GPIO_setDirectionMode(92, GPIO_DIR_MODE_OUT);       //DSP_GPIO92_DSP_XA0
	GPIO_setDirectionMode(38, GPIO_DIR_MODE_OUT);       //DSP_GPIO38_DSP_XA0(1)
	GPIO_setDirectionMode(39, GPIO_DIR_MODE_OUT);       //DSP_GPIO39_DSP_XA1(2)
	GPIO_setDirectionMode(40, GPIO_DIR_MODE_OUT);       //DSP_GPIO40_DSP_XA2(3)
	GPIO_setDirectionMode(41, GPIO_DIR_MODE_OUT);       //DSP_GPIO41_DSP_XA3(4)
	GPIO_setDirectionMode(34, GPIO_DIR_MODE_OUT);       //DSP_GPIO34_N_CS2
	GPIO_setDirectionMode(37, GPIO_DIR_MODE_OUT);       //DSP_GPIO37_N_XRD
	GPIO_setDirectionMode(31, GPIO_DIR_MODE_OUT);       //DSP_GPIO31_N_XWE

	GPIO_setQualificationMode(14, GPIO_QUAL_ASYNC);     //DSP_GPIO14_I_MASTER_RDAC_RDY()
	GPIO_setQualificationMode(15, GPIO_QUAL_ASYNC);     //DSP_GPIO15_I_SLAVE_RDAC_RDY()
	GPIO_setQualificationMode(32, GPIO_QUAL_ASYNC);     //DSP_GPIO32_I_EXT_SYNCH_SLAVE_IN()
	GPIO_setQualificationMode(61, GPIO_QUAL_ASYNC);     //DSP_GPIO61_I_ADC_BUSY()
	GPIO_setQualificationMode(63, GPIO_QUAL_ASYNC);     //DSP_GPIO63_I_ADC_FRSTD()
	GPIO_setQualificationMode(65, GPIO_QUAL_ASYNC);     //DSP_GPIO65_I_EMERGENCY_IN()

	GPIO_setQualificationMode(16, GPIO_QUAL_ASYNC);     //DSP_GPIO16_SPISIMOA
	GPIO_setQualificationMode(17, GPIO_QUAL_ASYNC);     //DSP_GPIO17_SPISOMIA
	GPIO_setQualificationMode(18, GPIO_QUAL_ASYNC);     //DSP_GPIO18_SPICLKA

	GPIO_setQualificationMode(23, GPIO_QUAL_ASYNC);     //DSP_GPIO23_SCIRXDB

	GPIO_setQualificationMode(24, GPIO_QUAL_ASYNC);     //DSP_GPIO24_SPISIMOB
	GPIO_setQualificationMode(25, GPIO_QUAL_ASYNC);     //DSP_GPIO25_SPISOMIB
	GPIO_setQualificationMode(26, GPIO_QUAL_ASYNC);     //DSP_GPIO26_SPICLKB
	GPIO_setQualificationMode(27, GPIO_QUAL_ASYNC);     //DSP_GPIO27_SPISTEB

	GPIO_setQualificationMode(28, GPIO_QUAL_ASYNC);     //DSP_GPIO28_SCIRXDA

	GPIO_setQualificationMode(85, GPIO_QUAL_ASYNC);     //DSP_GPIO85_DSP_XD0
	GPIO_setQualificationMode(83, GPIO_QUAL_ASYNC);     //DSP_GPIO83_DSP_XD1
	GPIO_setQualificationMode(82, GPIO_QUAL_ASYNC);     //DSP_GPIO82_DSP_XD2
	GPIO_setQualificationMode(81, GPIO_QUAL_ASYNC);     //DSP_GPIO81_DSP_XD3
	GPIO_setQualificationMode(80, GPIO_QUAL_ASYNC);     //DSP_GPIO80_DSP_XD4
	GPIO_setQualificationMode(79, GPIO_QUAL_ASYNC);     //DSP_GPIO79_DSP_XD5
	GPIO_setQualificationMode(78, GPIO_QUAL_ASYNC);     //DSP_GPIO78_DSP_XD6
	GPIO_setQualificationMode(77, GPIO_QUAL_ASYNC);     //DSP_GPIO77_DSP_XD7
	GPIO_setQualificationMode(76, GPIO_QUAL_ASYNC);     //DSP_GPIO76_DSP_XD8
	GPIO_setQualificationMode(75, GPIO_QUAL_ASYNC);     //DSP_GPIO75_DSP_XD9
	GPIO_setQualificationMode(74, GPIO_QUAL_ASYNC);     //DSP_GPIO74_DSP_XD10
	GPIO_setQualificationMode(73, GPIO_QUAL_ASYNC);     //DSP_GPIO73_DSP_XD11
	GPIO_setQualificationMode(72, GPIO_QUAL_ASYNC);     //DSP_GPIO72_DSP_XD12
	GPIO_setQualificationMode(71, GPIO_QUAL_ASYNC);     //DSP_GPIO71_DSP_XD13
	GPIO_setQualificationMode(70, GPIO_QUAL_ASYNC);     //DSP_GPIO70_DSP_XD14
	GPIO_setQualificationMode(69, GPIO_QUAL_ASYNC);     //DSP_GPIO69_DSP_XD15

//	GPIO_setPadConfig(24, GPIO_PIN_TYPE_PULLUP);
//	GPIO_setPadConfig(25, GPIO_PIN_TYPE_PULLUP);
//	GPIO_setPadConfig(26, GPIO_PIN_TYPE_PULLUP);
//	GPIO_setPadConfig(27, GPIO_PIN_TYPE_PULLUP);
//	GPIO_setPadConfig(85, GPIO_PIN_TYPE_PULLUP);
//	GPIO_setPadConfig(83, GPIO_PIN_TYPE_PULLUP);
//	GPIO_setPadConfig(82, GPIO_PIN_TYPE_PULLUP);
//	GPIO_setPadConfig(81, GPIO_PIN_TYPE_PULLUP);
//	GPIO_setPadConfig(80, GPIO_PIN_TYPE_PULLUP);
//	GPIO_setPadConfig(79, GPIO_PIN_TYPE_PULLUP);
//	GPIO_setPadConfig(78, GPIO_PIN_TYPE_PULLUP);
//	GPIO_setPadConfig(77, GPIO_PIN_TYPE_PULLUP);
//	GPIO_setPadConfig(76, GPIO_PIN_TYPE_PULLUP);
//	GPIO_setPadConfig(75, GPIO_PIN_TYPE_PULLUP);
//	GPIO_setPadConfig(74, GPIO_PIN_TYPE_PULLUP);
//	GPIO_setPadConfig(73, GPIO_PIN_TYPE_PULLUP);
//	GPIO_setPadConfig(72, GPIO_PIN_TYPE_PULLUP);
//	GPIO_setPadConfig(71, GPIO_PIN_TYPE_PULLUP);
//	GPIO_setPadConfig(70, GPIO_PIN_TYPE_PULLUP);
//	GPIO_setPadConfig(69, GPIO_PIN_TYPE_PULLUP);
//	GPIO_setPadConfig(92, GPIO_PIN_TYPE_PULLUP);
//	GPIO_setPadConfig(38, GPIO_PIN_TYPE_PULLUP);
//	GPIO_setPadConfig(39, GPIO_PIN_TYPE_PULLUP);
//	GPIO_setPadConfig(40, GPIO_PIN_TYPE_PULLUP);
//	GPIO_setPadConfig(41, GPIO_PIN_TYPE_PULLUP);



	DSP_GPIO00_O_OUTPUT_MASTER_CHARGE_CLEAR()
	DSP_GPIO01_O_OUTPUT_MASTER_DISCHARGE_CLEAR()
	DSP_GPIO02_O_OUTPUT_SLAVE_CHARGE_CLEAR()
	DSP_GPIO03_O_OUTPUT_SLAVE_DISCHARGE_CLEAR()
	DSP_GPIO04_O_OPMODE_MASTER_SEL0_CLEAR()
	DSP_GPIO05_O_OPMODE_MASTER_SEL1_CLEAR()
	DSP_GPIO06_O_OPMODE_SLAVE_SEL0_CLEAR()
	DSP_GPIO07_O_OPMODE_SLAVE_SEL1_CLEAR()
	DSP_GPIO08_O_INTG_MASTER_SEL0_CLEAR()
	DSP_GPIO09_O_INTG_MASTER_SEL1_CLEAR()
	DSP_GPIO50_O_INTG_MASTER_SEL2_CLEAR()
	DSP_GPIO10_O_INTG_RESET_SEL0_CLEAR()
	DSP_GPIO11_O_INTG_RESET_SEL1_CLEAR()
	DSP_GPIO12_O_INTG_SLAVE_SEL0_CLEAR()
	DSP_GPIO13_O_INTG_SLAVE_SEL1_CLEAR()
	DSP_GPIO51_O_INTG_SLAVE_SEL2_CLEAR()
	DSP_GPIO52_O_INTG_CHARGE_SEL0_CLEAR()
	DSP_GPIO53_O_INTG_CHARGE_SEL1_CLEAR()
	DSP_GPIO19_O_ENABLE_IO_1_CLEAR()
	DSP_GPIO20_O_ENABLE_IO_0_CLEAR()
	DSP_GPIO33_O_EXT_SYNCH_MASTER_CLEAR()
	DSP_GPIO42_O_N_MASTER_DIS_EN1_CLEAR()
	DSP_GPIO43_O_N_MASTER_DIS_EN0_CLEAR()
	DSP_GPIO44_O_N_MASTER_CHG_EN1_CLEAR()
	DSP_GPIO45_O_N_MASTER_CHG_EN0_CLEAR()
	DSP_GPIO46_O_N_SLAVE_DIS_EN1_CLEAR()
	DSP_GPIO47_O_N_SLAVE_DIS_EN0_CLEAR()
	DSP_GPIO48_O_N_SLAVE_CHG_EN1_CLEAR()
	DSP_GPIO49_O_N_SLAVE_CHG_EN0_CLEAR()
	DSP_GPIO54_O_DIO_PORT_1_CLEAR()
	DSP_GPIO55_O_DIO_PORT_0_CLEAR()
	DSP_GPIO56_O_P_VOLATAGE_RELAY_CLEAR()
	DSP_GPIO57_O_N_VOLATAGE_RELAY_CLEAR()
	DSP_GPIO58_O_ADC_OS0_CLEAR()
	DSP_GPIO59_O_ADC_OS1_CLEAR()
	DSP_GPIO60_O_ADC_OS2_CLEAR()
	DSP_GPIO62_O_ADC_N_CS_CLEAR()
	DSP_GPIO64_O_ADC_RESET_CLEAR()
	DSP_GPIO88_O_ADC_RANGE_CLEAR()
	DSP_GPIO66_O_DAC_A0_CLEAR()
	DSP_GPIO67_O_DAC_A1_CLEAR()
	DSP_GPIO68_O_DAC_FINE_I_N_RESET_CLEAR()
	DSP_GPIO86_O_DAC_V_N_RESET_CLEAR()
	DSP_GPIO87_O_DAC_I_N_RESET_CLEAR()
	DSP_GPIO89_O_MASTER_RDAC_N_RESET_CLEAR()
	DSP_GPIO90_O_MASTER_RDAC_N_CS_CLEAR()
	DSP_GPIO91_O_SLAVE_RDAC_N_RESET_CLEAR()
	DSP_GPIO93_O_SLAVE_RDAC_N_CS_CLEAR()
	DSP_GPIO94_O_N_RLYON_1_CLEAR()
	DSP_GPIO99_O_N_RLYON_0_CLEAR()
	DSP_GPIO133_O_DSP_STATUS_CLEAR()

//	GPIO_setPinConfig(GPIO_31_GPIO31);
//	GPIO_setDirectionMode(31, GPIO_DIR_MODE_OUT);
//
//	GPIO_setPinConfig(GPIO_34_GPIO34);
//	GPIO_setDirectionMode(34, GPIO_DIR_MODE_OUT);
//    GPIO_setMasterCore(DEVICE_GPIO_PIN_LED2, GPIO_CORE_CPU2);

}

//
// End of file
//
