/*
 * PhoenixonControls_CRC16.h
 *
 *  Created on: 2018. 6. 6.
 *      Author: BGKim
 */

#ifndef PHOENIXON_CONTROLS_CPU_INCLUDE_PHOENIXONCONTROLS_CRC16_H_
#define PHOENIXON_CONTROLS_CPU_INCLUDE_PHOENIXONCONTROLS_CRC16_H_

#define CRC16_  921600 // bps
Uint16 CRC16_Conversion(Uint16 *ui_Data, Uint16 ui_Length);

#endif /* PHOENIXON_CONTROLS_CPU_INCLUDE_PHOENIXONCONTROLS_CRC16_H_ */
