/*
 * PhoenixonControls_ADC.h
 *
 *  Created on: 2018. 5. 20.
 *      Author: BGKim
 */

#ifndef PHOENIXON_CONTROLS_CPU_INCLUDE_PHOENIXONCONTROLS_ADC_H_
#define PHOENIXON_CONTROLS_CPU_INCLUDE_PHOENIXONCONTROLS_ADC_H_

#define DSP_REFERENCE_VOLTAGE (float)(3.0)
#define DSP_RESOLUTION (float)(4096.0)
#define DSP_ADC_GAIN (float)(0.000732421875) //(DSP_REFERENCE_VOLTAGE / DSP_RESOLUTION)

void DSP_ADCInit(void);
Uint16 DSP_ADCRead(float32 *Data);

#endif /* PHOENIXON_CONTROLS_CPU_INCLUDE_PHOENIXONCONTROLS_ADC_H_ */
