/*
 * PhoenixonControls_CALIBRATION.h
 *
 *  Created on: 2018. 5. 20.
 *      Author: BGKim
 */

#ifndef PHOENIXON_CONTROLS_CPU_INCLUDE_PHOENIXONCONTROLS_CALIBRATION_H_
#define PHOENIXON_CONTROLS_CPU_INCLUDE_PHOENIXONCONTROLS_CALIBRATION_H_

#define CALIBRATION_VOLATAGE_UNIT_VALUE        (1.0)
#define CALIBRATION_VOLATAGE_MIN_VALUE         (0.0)
#define CALIBRATION_VOLATAGE_MAX_VALUE         (5.0)
#define CALIBRATION_VOLATAGE_MAX_ARRAY_LENGTH  (Uint16)(((CALIBRATION_VOLATAGE_MAX_VALUE - CALIBRATION_VOLATAGE_MIN_VALUE) / (CALIBRATION_VOLATAGE_UNIT_VALUE)) + 1.0)

#define CALIBRATION_CURRENT_UNIT_VALUE         (10.0)
#define CALIBRATION_CURRENT_MIN_VALUE          (0.0)
#if (Current_Spec == 200)
#define CALIBRATION_CURRENT_MAX_VALUE          (210.0)
#elif (Current_Spec == 300)
#define CALIBRATION_CURRENT_MAX_VALUE          (310.0)
#endif

#define CALIBRATION_CURRENT_MAX_ARRAY_LENGTH   (Uint16)(((CALIBRATION_CURRENT_MAX_VALUE - CALIBRATION_CURRENT_MIN_VALUE) / (CALIBRATION_CURRENT_UNIT_VALUE)) + 1.0)

#define CALIBRATION_LOW_CURRENT_UNIT_VALUE          (1.0)
#define CALIBRATION_LOW_CURRENT_MIN_VALUE           (0.0)
#define CALIBRATION_LOW_CURRENT_MAX_VALUE           (11.0)
#define CALIBRATION_LOW_CURRENT_MAX_ARRAY_LENGTH    (Uint16)(((CALIBRATION_LOW_CURRENT_MAX_VALUE - CALIBRATION_LOW_CURRENT_MIN_VALUE) / (CALIBRATION_LOW_CURRENT_UNIT_VALUE)) + 1.0)

extern float32 VoltageCharge_REF[CALIBRATION_VOLATAGE_MAX_ARRAY_LENGTH];
extern float32 VoltageDischarge_REF[CALIBRATION_VOLATAGE_MAX_ARRAY_LENGTH];
extern float32 VoltageCharge_ADC[CALIBRATION_VOLATAGE_MAX_ARRAY_LENGTH];
extern float32 VoltageDischarge_ADC[CALIBRATION_VOLATAGE_MAX_ARRAY_LENGTH];

extern float32 CurrentCharge_REF[CALIBRATION_CURRENT_MAX_ARRAY_LENGTH];
extern float32 CurrentDischarge_REF[CALIBRATION_CURRENT_MAX_ARRAY_LENGTH];
extern float32 CurrentCharge_ADC[CALIBRATION_CURRENT_MAX_ARRAY_LENGTH];
extern float32 CurrentDischarge_ADC[CALIBRATION_CURRENT_MAX_ARRAY_LENGTH];

float32 CALIBRATION_ConversionREF(float REF_Data, float *CAL_Data, float InitialValue, float Unit, Uint16 ArrayLength);
float32 CALIBRATION_ConversionCurrentADC(float32 ADC_Data, float32 *Measure_Data, float32 *CAL_Data, float32 InitialValue, float32 Unit, Uint16 ArrayLength);
float32 CALIBRATION_ConversionVoltageADC(float32 ADC_Data, float32 *CAL_Data, float32 InitialValue, float32 Unit, Uint16 ArrayLength);

#endif /* PHOENIXON_CONTROLS_CPU_INCLUDE_PHOENIXONCONTROLS_CALIBRATION_H_ */
